source 'https://rubygems.org'

# OUTPUTS
# gem 'gelf', '3.1.0' #output
# gem 'snappy', '0.3.0' #output
# gem 'fluent-plugin-s3', '1.7.2' #output
# gem 'fluent-plugin-azure-storage-append-blob', '0.2.1' #output, azurestore
#gem 'yajl-ruby', '1.4.3' #CloudWatchOutput
#gem 'oj', '3.16.1'#	// With default behavior, OpenSearch client uses Yajl as JSON encoder/decoder. Oj is the alternative high performance JSON encoder/decoder. When this parameter sets as true, OpenSearch client uses Oj as JSON encoder/decoder.
# gem 'fluent-plugin-aliyun-oss', '0.0.1'#output, OSSOutput
# gem 'fluent-plugin-sumologic_output', '1.8.0' #output?
# gem 'fluent-plugin-kafka', '0.19.1' #output?
# gem 'fluent-plugin-grafana-loki', '1.2.20' #output
# gem 'fluent-plugin-kinesis', '3.4.2' #output
# gem 'fluent-plugin-splunk-hec', '1.3.3' #output?
# gem 'fluent-plugin-elasticsearch', '5.3.0'# output?
# gem 'fluent-plugin-newrelic', '1.2.2' #output
# gem 'fluent-plugin-cloudwatch-logs', '0.14.3' #output
# gem 'fluent-plugin-opensearch', '1.1.4' #output
# gem 'fluent-plugin-logzio', '0.2.2' #output
# # gem 'fluent-plugin-logdna', '~> 0.4.0' #output
# gem 'fluent-plugin-datadog', '0.14.2' #output
# gem 'fluent-plugin-redis', '0.3.5' #output
# gem 'fluent-plugin-gelf-hs', '1.0.8' #output
# gem 'fluent-plugin-sqs', '3.0.0' #output
# gem 'fluent-plugin-mattermost', '0.2.2' #output
# gem 'fluent-plugin-syslog_rfc5424', :git => 'https://github.com/acquia/fluent-plugin-syslog_rfc5424.git', :tag => '0.2.1' #output
# gem 'fluent-plugin-gcs', :git => 'https://github.com/kube-logging/fluent-plugin-gcs.git', :branch => 'master' #output

# # FILTERS
# gem 'fluent-plugin-detect-exceptions', '0.0.15' # filter
# gem 'fluent-plugin-prometheus', '2.1.0' #filter
# gem 'fluent-plugin-dedot_filter', '1.0.0' #filter, DedotFilterConfig
# gem 'fluent-plugin-geoip', '1.3.2' #filter
# gem 'fluent-plugin-tag-normaliser', '0.1.2'#filter
# gem 'fluent-plugin-concat', '2.5.0' #filter
# gem 'fluent-plugin-parser-logfmt', '0.0.0'#filter?
# gem 'fluent-plugin-record-modifier', '2.1.1' #filter
# gem 'fluent-plugin-kube-events-timestamp', '0.1.3' #filter
# gem 'fluent-plugin-throttle', '0.0.5' #filter
# gem 'fluent-plugin-enhance-k8s-metadata', :git => 'https://github.com/SumoLogic/sumologic-kubernetes-fluentd.git', :tag => 'v1.16.2-sumo-0', :glob => 'fluent-plugin-enhance-k8s-metadata/*.gemspec' #filter

# UNKNOWNS
# gem 'elasticsearch', '8.10.0'
# gem 'elasticsearch-xpack', '7.17.9'
# gem 'activesupport', '6.1.7.5'
#gem 'http_parser.rb', '0.8.0'
#gem 'tzinfo', '>= 1.2.11'
#gem 'resolv', '0.2.2'
#gem 'json', '2.6.3'
#gem 'async', '1.31.0'
#gem 'async-http', '0.60.2'
gem 'fluentd', '1.16.2'
#gem 'prometheus-client', '4.2.1'
# gem 'bigdecimal', '3.1.4'
#gem 'webrick', '1.8.1'

# gem 'fluent-plugin-remote-syslog', '1.1.0'
# gem 'fluent-plugin-webhdfs', '1.5.0'
# gem 'fluent-plugin-rewrite-tag-filter', '2.4.0'
# gem 'fluent-plugin-multi-format-parser', '1.0.0'
# 
# gem 'fluent-plugin-aws-elasticsearch-service', '2.4.1'
# gem 'fluent-plugin-grok-parser', '2.6.2'
# 
# gem 'fluent-plugin-vmware-loginsight', '1.4.1'
# gem 'fluent-plugin-vmware-log-intelligence', '2.0.8'
# gem 'fluent-plugin-mysqlslowquery', '0.0.9'

gem 'fluent-plugin-label-router', :git => 'https://github.com/kube-logging/fluent-plugin-label-router.git', :ref => '2ff43789f895735b7852e0a1a809280e22d9e8ef' #router
#gem 'fluent-plugin-kubernetes-metadata-filter', :git => 'https://github.com/SumoLogic/sumologic-kubernetes-fluentd.git', :tag => 'v1.16.2-sumo-0', :glob => 'fluent-plugin-kubernetes-metadata-filter/*.gemspec'
# gem 'fluent-plugin-kubernetes-sumologic', :git => 'https://github.com/SumoLogic/sumologic-kubernetes-fluentd.git', :tag => 'v1.16.2-sumo-0', :glob => 'fluent-plugin-kubernetes-sumologic/*.gemspec'
# gem 'kubeclient', :git => 'https://github.com/abonas/kubeclient.git', :tag => 'v4.11.0'